export enum Routes {
  Root = '/',
  Contact = '/contact-us',
  Features = '/features',
  SummaryFeatures = '/summary-features',
  WhyUserSolutions = '/why-user-solutions',
  Mission = '/mission-statement',
  Solutions = '/solutions',
  ProductionPlanning = '/production-planning-scheduling-solutions',
  Values = '/values',
  History = '/company-history',
  About = '/about',
  Partners = '/partners',
  SuccessStories = '/success-stories',
  ExcelTemplates = '/excel-templates',
  ProductVideos = '/videos',
  ResourceManagement = '/resource-management-blog',
  JobSchedulerLite = '/jsl-job-scheduler-lite',
  JobSchedulerLiteDownload = '/jsl-job-scheduler-lite-download',
  Edgebi = '/edgebi',
  OperationsManager = '/operations-manager',
  Roadmap = 'https://achromatic.canny.io',
  Docs = '/docs',
  Pricing = '/pricing',
  Blog = '/blog',
  Calendar = '/dashboard/calendar',
  News = '/news',
  ProductDownloads = '/product-downloads',
  Students = '/students',
  Product2 = '/product-2',
  Story = '/story',
  SleepmasterLtd = '/sleepmaster-ltd',
  CookCompression = '/cook-compression',
  InconIncorporated = '/incon-incorporated',
  TermsOfUse = '/terms-of-use',
  PrivacyPolicy = '/privacy-policy',
  CookiePolicy = '/cookie-policy',

  // New pages from sitemap
  Shop = '/shop',
  Cart = '/cart',
  Checkout = '/checkout',
  Blogs = '/blogs',
  PressRelease = '/press_release',
  ThankYouSpreadsheetScheduler = '/thankyou-for-downloading-spreadsheet-scheduler',
  ThankYouJSL = '/thankyou-for-downloading-jsl',
  OperationsManagerApp = '/operations-manager-app',

  Auth = '/auth',
  Login = '/auth/login',
  Logout = '/auth/logout',
  SignUp = '/auth/signup',
  AuthError = '/auth/error',
  Totp = '/auth/totp',
  RecoveryCode = '/auth/recovery-code',
  ChangeEmail = '/auth/change-email',
  ChangeEmailRequest = '/auth/change-email/request',
  ChangeEmailInvalid = '/auth/change-email/invalid',
  ChangeEmailExpired = '/auth/change-email/expired',
  ForgotPassword = '/auth/forgot-password',
  ForgotPasswordSuccess = '/auth/forgot-password/success',
  ResetPassword = '/auth/reset-password',
  ResetPasswordRequest = '/auth/reset-password/request',
  ResetPasswordExpired = '/auth/reset-password/expired',
  ResetPasswordSuccess = '/auth/reset-password/success',
  VerifyEmail = '/auth/verify-email',
  VerifyEmailRequest = '/auth/verify-email/request',
  VerifyEmailExpired = '/auth/verify-email/expired',
  VerifyEmailSuccess = '/auth/verify-email/success',

  Home = '/dashboard',
  Analytics = '/dashboard/analytics',
  Contacts = '/dashboard/contacts',
  Inventory = '/dashboard/inventory',
  Settings = '/dashboard/settings',
  Account = '/dashboard/settings/account',
  Profile = '/dashboard/settings/account/profile',
  Security = '/dashboard/settings/account/security',
  Notifications = '/dashboard/settings/account/notifications',
  Organization = '/dashboard/settings/organization',
  OrganizationInformation = '/dashboard/settings/organization/information',
  Members = '/dashboard/settings/organization/members',
  Billing = '/dashboard/settings/organization/billing',
  Developers = '/dashboard/settings/organization/developers',

  Invitations = '/invitations',
  InvitationRequest = '/invitations/request',
  InvitationAlreadyAccepted = '/invitations/already-accepted',
  InvitationRevoked = '/invitations/revoked',
  InvitationLogOutToAccept = '/invitations/log-out-to-accept',

  Onboarding = '/onboarding',
  FAQ = '/faq',

  // Industry landing pages
  JobShopScheduling = '/scheduling-software-for-job-shops',
  DefenseAerospace = '/defense-aerospace-manufacturing-scheduling',
  ElectronicsManufacturing = '/electronics-manufacturing-scheduling-software',
  HeavyEquipment = '/heavy-equipment-manufacturing-scheduling',
  ConsumerGoods = '/consumer-goods-production-planning-software',

  // Feature landing pages
  ProductionSchedulingSoftware = '/production-scheduling-software',
  FiniteCapacityScheduling = '/finite-capacity-scheduling-software',
  ManufacturingSchedulingSoftware = '/manufacturing-scheduling-software',
  MrpSoftwareSmallManufacturers = '/mrp-software-small-manufacturers',
  ErpSchedulingAddOn = '/erp-scheduling-add-on',
  WhatIfAnalysis = '/what-if-analysis-manufacturing',
  MultiLocationScheduling = '/multi-location-manufacturing-scheduling',
  BomSoftware = '/bill-of-materials-bom-software',
  MasterProductionSchedule = '/master-production-schedule-software',
  LaborScheduling = '/labor-scheduling-manufacturing',
  ExcelToScheduling = '/excel-to-scheduling-software',
  OnTimeDelivery = '/on-time-delivery-manufacturing',
  ErpIntegration = '/erp-integration-production-scheduling'
}
