// 205 SEO target keywords for usersolutions.com (User Solutions / EDGEBIC).
// Source: Master keyword list provided 2026-04-10.
// Volume/KD numbers are ESTIMATED — verify in Ahrefs Keywords Explorer before
// making strategic decisions. This file is the input to build-keyword-tracker.mjs.
//
// Fields:
//   id       — stable 1..205 identifier
//   keyword  — exact target phrase
//   vol      — estimated US monthly search volume
//   kd       — Ahrefs-style keyword difficulty (0–100)
//   intent   — T (transactional) | C (commercial) | I (informational)
//   tier     — 1 money | 2 alternatives | 3 templates | 4 industries | 5 informational | local | brand
//   priority — now | q2 | q3-q4
//   suggestedUrl — the URL the user originally proposed (may not exist; tracker remaps)

export const KEYWORDS = [
  // ─────────────── TIER 1 — MONEY KEYWORDS ───────────────
  { id: 1, keyword: 'production scheduling software', vol: 2400, kd: 55, intent: 'T', tier: 1, priority: 'now', suggestedUrl: '/resource-manager-db-2' },
  { id: 2, keyword: 'manufacturing scheduling software', vol: 1600, kd: 52, intent: 'T', tier: 1, priority: 'now', suggestedUrl: '/resource-manager-db-2' },
  { id: 3, keyword: 'production planning software', vol: 2900, kd: 58, intent: 'T', tier: 1, priority: 'now', suggestedUrl: '/resource-manager-db-2' },
  { id: 4, keyword: 'finite capacity scheduling software', vol: 400, kd: 38, intent: 'T', tier: 1, priority: 'now', suggestedUrl: '/finite-capacity-scheduling-software' },
  { id: 5, keyword: 'advanced planning and scheduling software', vol: 720, kd: 48, intent: 'T', tier: 1, priority: 'now', suggestedUrl: '/resource-manager-db-2' },
  { id: 6, keyword: 'APS software', vol: 1000, kd: 45, intent: 'T', tier: 1, priority: 'now', suggestedUrl: '/resource-manager-db-2' },
  { id: 7, keyword: 'production scheduling tool', vol: 480, kd: 42, intent: 'T', tier: 1, priority: 'q2', suggestedUrl: '/resource-manager-db-2' },
  { id: 8, keyword: 'manufacturing planning software', vol: 880, kd: 50, intent: 'T', tier: 1, priority: 'q2', suggestedUrl: '/resource-manager-db-2' },
  { id: 9, keyword: 'shop floor scheduling software', vol: 320, kd: 35, intent: 'T', tier: 1, priority: 'q2', suggestedUrl: '/scheduling-software-for-job-shops' },
  { id: 10, keyword: 'production scheduler software', vol: 390, kd: 40, intent: 'T', tier: 1, priority: 'q2', suggestedUrl: '/resource-manager-db-2' },
  { id: 11, keyword: 'manufacturing business intelligence', vol: 590, kd: 40, intent: 'T', tier: 1, priority: 'now', suggestedUrl: '/edgebi' },
  { id: 12, keyword: 'manufacturing BI software', vol: 390, kd: 38, intent: 'T', tier: 1, priority: 'now', suggestedUrl: '/edgebi' },
  { id: 13, keyword: 'production analytics software', vol: 320, kd: 35, intent: 'T', tier: 1, priority: 'q2', suggestedUrl: '/edgebi' },
  { id: 14, keyword: 'factory dashboard software', vol: 210, kd: 30, intent: 'T', tier: 1, priority: 'q2', suggestedUrl: '/edgebi' },
  { id: 15, keyword: 'shop floor analytics', vol: 260, kd: 32, intent: 'T', tier: 1, priority: 'q2', suggestedUrl: '/edgebi' },
  { id: 16, keyword: 'manufacturing KPI dashboard', vol: 480, kd: 35, intent: 'T', tier: 1, priority: 'q2', suggestedUrl: '/edgebi' },
  { id: 17, keyword: 'real time manufacturing dashboard', vol: 170, kd: 28, intent: 'T', tier: 1, priority: 'q3-q4', suggestedUrl: '/edgebi' },
  { id: 18, keyword: 'excel production scheduling', vol: 880, kd: 30, intent: 'T', tier: 1, priority: 'now', suggestedUrl: '/resource-manager-for-excel-2' },
  { id: 19, keyword: 'excel scheduling software', vol: 720, kd: 35, intent: 'T', tier: 1, priority: 'now', suggestedUrl: '/resource-manager-for-excel-2' },
  { id: 20, keyword: 'production planning excel tool', vol: 390, kd: 25, intent: 'T', tier: 1, priority: 'now', suggestedUrl: '/resource-manager-for-excel-2' },
  { id: 21, keyword: 'excel based scheduling', vol: 260, kd: 22, intent: 'T', tier: 1, priority: 'q2', suggestedUrl: '/resource-manager-for-excel-2' },
  { id: 22, keyword: 'excel gantt chart software', vol: 590, kd: 38, intent: 'T', tier: 1, priority: 'q2', suggestedUrl: '/resource-manager-for-excel-2' },
  { id: 23, keyword: 'excel capacity planning', vol: 480, kd: 28, intent: 'T', tier: 1, priority: 'q2', suggestedUrl: '/resource-manager-for-excel-2' },
  { id: 24, keyword: 'job scheduler software', vol: 1300, kd: 45, intent: 'T', tier: 1, priority: 'q2', suggestedUrl: '/jsl-job-scheduler-lite' },
  { id: 25, keyword: 'simple scheduling software', vol: 590, kd: 40, intent: 'T', tier: 1, priority: 'q2', suggestedUrl: '/jsl-job-scheduler-lite' },
  { id: 26, keyword: 'small business scheduling software', vol: 1900, kd: 55, intent: 'T', tier: 1, priority: 'q3-q4', suggestedUrl: '/jsl-job-scheduler-lite' },
  { id: 27, keyword: 'affordable scheduling software', vol: 320, kd: 35, intent: 'T', tier: 1, priority: 'q3-q4', suggestedUrl: '/jsl-job-scheduler-lite' },
  { id: 28, keyword: 'job scheduling tool', vol: 480, kd: 38, intent: 'T', tier: 1, priority: 'q3-q4', suggestedUrl: '/jsl-job-scheduler-lite' },

  // ─────────────── TIER 2 — ALTERNATIVES / COMPARISONS ───────────────
  { id: 29, keyword: 'MRPeasy alternative', vol: 140, kd: 15, intent: 'C', tier: 2, priority: 'now', suggestedUrl: '/compare-products/rmdb-vs-mrpeasy' },
  { id: 30, keyword: 'MRPeasy alternatives', vol: 170, kd: 18, intent: 'C', tier: 2, priority: 'now', suggestedUrl: '/compare-products/rmdb-vs-mrpeasy' },
  { id: 31, keyword: 'MRPeasy vs', vol: 210, kd: 20, intent: 'C', tier: 2, priority: 'now', suggestedUrl: '/compare-products/rmdb-vs-mrpeasy' },
  { id: 32, keyword: 'MRPeasy competitors', vol: 90, kd: 12, intent: 'C', tier: 2, priority: 'now', suggestedUrl: '/compare-products/rmdb-vs-mrpeasy' },
  { id: 33, keyword: 'PlanetTogether alternative', vol: 90, kd: 14, intent: 'C', tier: 2, priority: 'now', suggestedUrl: '/compare-products/rmdb-vs-planettogether' },
  { id: 34, keyword: 'PlanetTogether alternatives', vol: 70, kd: 12, intent: 'C', tier: 2, priority: 'now', suggestedUrl: '/compare-products/rmdb-vs-planettogether' },
  { id: 35, keyword: 'PlanetTogether vs Preactor', vol: 40, kd: 10, intent: 'C', tier: 2, priority: 'q3-q4', suggestedUrl: '/compare-products/planettogether-vs-preactor' },
  { id: 36, keyword: 'Preactor alternative', vol: 70, kd: 12, intent: 'C', tier: 2, priority: 'now', suggestedUrl: '/compare-products/rmdb-vs-preactor' },
  { id: 37, keyword: 'Preactor alternatives', vol: 90, kd: 14, intent: 'C', tier: 2, priority: 'now', suggestedUrl: '/compare-products/rmdb-vs-preactor' },
  { id: 38, keyword: 'Katana alternative', vol: 320, kd: 25, intent: 'C', tier: 2, priority: 'now', suggestedUrl: '/compare-products/rmdb-vs-katana' },
  { id: 39, keyword: 'Katana MRP alternative', vol: 140, kd: 18, intent: 'C', tier: 2, priority: 'q2', suggestedUrl: '/compare-products/rmdb-vs-katana' },
  { id: 40, keyword: 'Fishbowl alternative', vol: 880, kd: 35, intent: 'C', tier: 2, priority: 'now', suggestedUrl: '/compare-products/rmdb-vs-fishbowl' },
  { id: 41, keyword: 'Fishbowl inventory alternative', vol: 390, kd: 28, intent: 'C', tier: 2, priority: 'now', suggestedUrl: '/compare-products/rmdb-vs-fishbowl' },
  { id: 42, keyword: 'JobBOSS alternative', vol: 210, kd: 20, intent: 'C', tier: 2, priority: 'q2', suggestedUrl: '/compare-products/rmdb-vs-jobboss' },
  { id: 43, keyword: 'E2 shop system alternative', vol: 170, kd: 18, intent: 'C', tier: 2, priority: 'q2', suggestedUrl: '/compare-products/rmdb-vs-e2-shop-system' },
  { id: 44, keyword: 'ProShop alternative', vol: 90, kd: 15, intent: 'C', tier: 2, priority: 'q2', suggestedUrl: '/compare-products/rmdb-vs-proshop' },
  { id: 45, keyword: 'Global Shop Solutions alternative', vol: 140, kd: 20, intent: 'C', tier: 2, priority: 'q2', suggestedUrl: '/compare-products/rmdb-vs-global-shop-solutions' },
  { id: 46, keyword: 'Epicor alternative small business', vol: 260, kd: 22, intent: 'C', tier: 2, priority: 'q2', suggestedUrl: '/compare-products/rmdb-vs-epicor' },
  { id: 47, keyword: 'NetSuite manufacturing alternative', vol: 320, kd: 30, intent: 'C', tier: 2, priority: 'q2', suggestedUrl: '/compare-products/rmdb-vs-netsuite' },
  { id: 48, keyword: 'SAP alternative small manufacturer', vol: 170, kd: 25, intent: 'C', tier: 2, priority: 'q3-q4', suggestedUrl: '/compare-products/rmdb-vs-sap' },
  { id: 49, keyword: 'Odoo manufacturing alternative', vol: 390, kd: 25, intent: 'C', tier: 2, priority: 'q3-q4', suggestedUrl: '/compare-products/rmdb-vs-odoo' },
  { id: 50, keyword: 'Quickbooks manufacturing alternative', vol: 260, kd: 22, intent: 'C', tier: 2, priority: 'q3-q4', suggestedUrl: '/compare-products/rmdb-vs-quickbooks' },
  { id: 51, keyword: 'cheaper than MRPeasy', vol: 30, kd: 8, intent: 'C', tier: 2, priority: 'q3-q4', suggestedUrl: '/compare-products/rmdb-vs-mrpeasy' },
  { id: 52, keyword: 'better than PlanetTogether', vol: 20, kd: 8, intent: 'C', tier: 2, priority: 'q3-q4', suggestedUrl: '/compare-products/rmdb-vs-planettogether' },
  { id: 53, keyword: 'best production scheduling software', vol: 1000, kd: 48, intent: 'C', tier: 2, priority: 'q2', suggestedUrl: '/blog/best-production-scheduling-software' },
  { id: 54, keyword: 'best production scheduling software for small business', vol: 210, kd: 30, intent: 'C', tier: 2, priority: 'now', suggestedUrl: '/blog/best-production-scheduling-software' },
  { id: 55, keyword: 'best manufacturing scheduling software', vol: 480, kd: 42, intent: 'C', tier: 2, priority: 'q2', suggestedUrl: '/blog/best-manufacturing-scheduling-software' },
  { id: 56, keyword: 'best APS software', vol: 170, kd: 35, intent: 'C', tier: 2, priority: 'q2', suggestedUrl: '/blog/best-aps-software' },
  { id: 57, keyword: 'production scheduling software comparison', vol: 140, kd: 30, intent: 'C', tier: 2, priority: 'q2', suggestedUrl: '/blog/production-scheduling-software-comparison' },
  { id: 58, keyword: 'top manufacturing software', vol: 390, kd: 45, intent: 'C', tier: 2, priority: 'q3-q4', suggestedUrl: '/blog/top-manufacturing-software' },
  { id: 59, keyword: 'manufacturing software reviews', vol: 320, kd: 40, intent: 'C', tier: 2, priority: 'q3-q4', suggestedUrl: '/blog/manufacturing-software-reviews' },
  { id: 60, keyword: 'cheap production scheduling software', vol: 90, kd: 25, intent: 'C', tier: 2, priority: 'q2', suggestedUrl: '/blog/cheap-production-scheduling-software' },
  { id: 61, keyword: 'free production scheduling software', vol: 720, kd: 35, intent: 'C', tier: 2, priority: 'q2', suggestedUrl: '/blog/free-production-scheduling-software' },

  // ─────────────── TIER 3 — EXCEL TEMPLATES ───────────────
  { id: 62, keyword: 'production schedule excel template', vol: 1300, kd: 25, intent: 'C', tier: 3, priority: 'now', suggestedUrl: '/excel-templates/production-schedule' },
  { id: 63, keyword: 'production planning excel template', vol: 1600, kd: 28, intent: 'C', tier: 3, priority: 'now', suggestedUrl: '/excel-templates/production-planning' },
  { id: 64, keyword: 'production schedule template excel free', vol: 720, kd: 20, intent: 'C', tier: 3, priority: 'now', suggestedUrl: '/excel-templates/production-schedule' },
  { id: 65, keyword: 'manufacturing schedule template excel', vol: 590, kd: 25, intent: 'C', tier: 3, priority: 'now', suggestedUrl: '/excel-templates/manufacturing-schedule' },
  { id: 66, keyword: 'capacity planning excel template', vol: 720, kd: 22, intent: 'C', tier: 3, priority: 'now', suggestedUrl: '/excel-templates/capacity-planning' },
  { id: 67, keyword: 'capacity planning template excel free', vol: 320, kd: 18, intent: 'C', tier: 3, priority: 'now', suggestedUrl: '/excel-templates/capacity-planning' },
  { id: 68, keyword: 'master production schedule excel template', vol: 480, kd: 25, intent: 'C', tier: 3, priority: 'now', suggestedUrl: '/excel-templates/master-production-schedule' },
  { id: 69, keyword: 'MPS excel template', vol: 210, kd: 20, intent: 'C', tier: 3, priority: 'q2', suggestedUrl: '/excel-templates/master-production-schedule' },
  { id: 70, keyword: 'gantt chart excel manufacturing', vol: 390, kd: 22, intent: 'C', tier: 3, priority: 'now', suggestedUrl: '/excel-templates/gantt-chart' },
  { id: 71, keyword: 'manufacturing gantt chart template', vol: 260, kd: 20, intent: 'C', tier: 3, priority: 'q2', suggestedUrl: '/excel-templates/gantt-chart' },
  { id: 72, keyword: 'job scheduling excel template', vol: 480, kd: 22, intent: 'C', tier: 3, priority: 'now', suggestedUrl: '/excel-templates/job-scheduling' },
  // #73 employee scheduling excel template — DROPPED 2026-04-10
  // Wrong-intent keyword: search audience is HR/restaurants/retail managers
  // scheduling worker shifts, not manufacturing operations. Manufacturing
  // labor scheduling uses different terminology. Removed from target list to
  // avoid wasting effort building content for the wrong audience.
  { id: 74, keyword: 'machine scheduling excel template', vol: 170, kd: 18, intent: 'C', tier: 3, priority: 'q2', suggestedUrl: '/excel-templates/machine-scheduling' },
  // #75 shift schedule excel template — DROPPED 2026-04-10
  // Wrong-intent keyword: same reason as #73. Generic worker shift scheduling
  // for HR/retail/healthcare audiences, not manufacturing production.
  { id: 76, keyword: 'work order excel template', vol: 1300, kd: 30, intent: 'C', tier: 3, priority: 'q2', suggestedUrl: '/excel-templates/work-order' },
  { id: 77, keyword: 'MRP excel template', vol: 590, kd: 25, intent: 'C', tier: 3, priority: 'q2', suggestedUrl: '/excel-templates/mrp' },
  { id: 78, keyword: 'bill of materials excel template', vol: 1000, kd: 30, intent: 'C', tier: 3, priority: 'q2', suggestedUrl: '/excel-templates/bill-of-materials' },
  { id: 79, keyword: 'inventory excel template manufacturing', vol: 480, kd: 28, intent: 'C', tier: 3, priority: 'q2', suggestedUrl: '/excel-templates/inventory' },
  { id: 80, keyword: 'production tracking excel template', vol: 390, kd: 22, intent: 'C', tier: 3, priority: 'q2', suggestedUrl: '/excel-templates/production-tracking' },
  { id: 81, keyword: 'OEE calculation excel template', vol: 320, kd: 20, intent: 'C', tier: 3, priority: 'q2', suggestedUrl: '/excel-templates/oee-calculation' },
  { id: 82, keyword: 'takt time calculator excel', vol: 260, kd: 18, intent: 'C', tier: 3, priority: 'q3-q4', suggestedUrl: '/excel-templates/takt-time-calculator' },
  { id: 83, keyword: 'production report excel template', vol: 590, kd: 25, intent: 'C', tier: 3, priority: 'q3-q4', suggestedUrl: '/excel-templates/production-report' },
  { id: 84, keyword: 'factory production planning excel', vol: 210, kd: 18, intent: 'C', tier: 3, priority: 'q3-q4', suggestedUrl: '/excel-templates/factory-production-planning' },

  // ─────────────── TIER 4 — INDUSTRIES ───────────────
  { id: 85, keyword: 'machine shop scheduling software', vol: 390, kd: 30, intent: 'T', tier: 4, priority: 'now', suggestedUrl: '/industries/machine-shops' },
  { id: 86, keyword: 'machine shop management software', vol: 720, kd: 40, intent: 'T', tier: 4, priority: 'now', suggestedUrl: '/industries/machine-shops' },
  { id: 87, keyword: 'CNC shop scheduling software', vol: 140, kd: 22, intent: 'T', tier: 4, priority: 'now', suggestedUrl: '/industries/cnc-shops' },
  { id: 88, keyword: 'CNC scheduling software', vol: 170, kd: 25, intent: 'T', tier: 4, priority: 'q2', suggestedUrl: '/industries/cnc-shops' },
  { id: 89, keyword: 'metal fabrication scheduling software', vol: 210, kd: 28, intent: 'T', tier: 4, priority: 'now', suggestedUrl: '/industries/metal-fabrication' },
  { id: 90, keyword: 'metal fabrication software', vol: 880, kd: 45, intent: 'T', tier: 4, priority: 'q2', suggestedUrl: '/industries/metal-fabrication' },
  { id: 91, keyword: 'sheet metal scheduling software', vol: 90, kd: 20, intent: 'T', tier: 4, priority: 'q2', suggestedUrl: '/industries/sheet-metal' },
  { id: 92, keyword: 'food manufacturing scheduling software', vol: 170, kd: 30, intent: 'T', tier: 4, priority: 'now', suggestedUrl: '/industries/food-manufacturing' },
  { id: 93, keyword: 'food production planning software', vol: 260, kd: 35, intent: 'T', tier: 4, priority: 'q2', suggestedUrl: '/industries/food-manufacturing' },
  { id: 94, keyword: 'bakery production planning software', vol: 90, kd: 22, intent: 'T', tier: 4, priority: 'q3-q4', suggestedUrl: '/industries/bakery' },
  { id: 95, keyword: 'beverage manufacturing software', vol: 320, kd: 35, intent: 'T', tier: 4, priority: 'q3-q4', suggestedUrl: '/industries/beverage' },
  { id: 96, keyword: 'aerospace production scheduling', vol: 90, kd: 25, intent: 'T', tier: 4, priority: 'q2', suggestedUrl: '/defense-aerospace-manufacturing-scheduling' },
  { id: 97, keyword: 'aerospace manufacturing software', vol: 480, kd: 40, intent: 'T', tier: 4, priority: 'q3-q4', suggestedUrl: '/defense-aerospace-manufacturing-scheduling' },
  { id: 98, keyword: 'injection molding scheduling software', vol: 110, kd: 25, intent: 'T', tier: 4, priority: 'q2', suggestedUrl: '/industries/injection-molding' },
  { id: 99, keyword: 'plastic manufacturing software', vol: 320, kd: 35, intent: 'T', tier: 4, priority: 'q3-q4', suggestedUrl: '/industries/plastics' },
  { id: 100, keyword: 'automotive parts scheduling software', vol: 90, kd: 25, intent: 'T', tier: 4, priority: 'q2', suggestedUrl: '/industries/automotive-parts' },
  { id: 101, keyword: 'electronics manufacturing software', vol: 720, kd: 42, intent: 'T', tier: 4, priority: 'q3-q4', suggestedUrl: '/electronics-manufacturing-scheduling-software' },
  { id: 102, keyword: 'PCB assembly scheduling', vol: 70, kd: 20, intent: 'T', tier: 4, priority: 'q3-q4', suggestedUrl: '/industries/pcb-assembly' },
  { id: 103, keyword: 'medical device manufacturing software', vol: 590, kd: 42, intent: 'T', tier: 4, priority: 'q3-q4', suggestedUrl: '/industries/medical-devices' },
  { id: 104, keyword: 'furniture manufacturing software', vol: 260, kd: 32, intent: 'T', tier: 4, priority: 'q3-q4', suggestedUrl: '/industries/furniture' },
  { id: 105, keyword: 'textile production planning software', vol: 170, kd: 30, intent: 'T', tier: 4, priority: 'q3-q4', suggestedUrl: '/industries/textile' },
  { id: 106, keyword: 'garment production planning software', vol: 210, kd: 32, intent: 'T', tier: 4, priority: 'q3-q4', suggestedUrl: '/industries/garment' },
  { id: 107, keyword: 'packaging manufacturing software', vol: 260, kd: 35, intent: 'T', tier: 4, priority: 'q3-q4', suggestedUrl: '/industries/packaging' },
  { id: 108, keyword: 'print shop scheduling software', vol: 320, kd: 30, intent: 'T', tier: 4, priority: 'q2', suggestedUrl: '/industries/print-shops' },
  { id: 109, keyword: 'print shop management software', vol: 590, kd: 38, intent: 'T', tier: 4, priority: 'q2', suggestedUrl: '/industries/print-shops' },
  { id: 110, keyword: 'job shop scheduling software', vol: 720, kd: 38, intent: 'T', tier: 4, priority: 'now', suggestedUrl: '/scheduling-software-for-job-shops' },
  { id: 111, keyword: 'job shop management software', vol: 480, kd: 35, intent: 'T', tier: 4, priority: 'now', suggestedUrl: '/scheduling-software-for-job-shops' },
  { id: 112, keyword: 'custom manufacturing scheduling', vol: 140, kd: 25, intent: 'T', tier: 4, priority: 'q2', suggestedUrl: '/scheduling-software-for-job-shops' },
  { id: 113, keyword: 'small manufacturer scheduling software', vol: 170, kd: 25, intent: 'T', tier: 4, priority: 'now', suggestedUrl: '/mrp-software-small-manufacturers' },
  { id: 114, keyword: 'small factory management software', vol: 260, kd: 30, intent: 'T', tier: 4, priority: 'q2', suggestedUrl: '/mrp-software-small-manufacturers' },
  { id: 115, keyword: 'mid-sized manufacturer software', vol: 140, kd: 28, intent: 'T', tier: 4, priority: 'q3-q4', suggestedUrl: '/resource-manager-db-2' },

  // ─────────────── TIER 5 — INFORMATIONAL ───────────────
  { id: 116, keyword: 'what is production scheduling', vol: 880, kd: 25, intent: 'I', tier: 5, priority: 'now', suggestedUrl: '/blog/what-is-production-scheduling' },
  { id: 117, keyword: 'what is APS software', vol: 210, kd: 20, intent: 'I', tier: 5, priority: 'now', suggestedUrl: '/blog/what-is-aps-software' },
  { id: 118, keyword: 'what is finite capacity scheduling', vol: 140, kd: 18, intent: 'I', tier: 5, priority: 'now', suggestedUrl: '/blog/what-is-finite-capacity-planning' },
  { id: 119, keyword: 'what is infinite scheduling', vol: 90, kd: 15, intent: 'I', tier: 5, priority: 'q2', suggestedUrl: '/blog/finite-vs-infinite-capacity-scheduling' },
  { id: 120, keyword: 'what is master production schedule', vol: 1300, kd: 28, intent: 'I', tier: 5, priority: 'now', suggestedUrl: '/blog/what-is-master-production-schedule' },
  { id: 121, keyword: 'what is MRP', vol: 6600, kd: 45, intent: 'I', tier: 5, priority: 'q3-q4', suggestedUrl: '/blog/what-is-mrp' },
  { id: 122, keyword: 'what is ERP', vol: 18100, kd: 65, intent: 'I', tier: 5, priority: 'q3-q4', suggestedUrl: '/blog/what-is-erp' },
  { id: 123, keyword: 'what is MES', vol: 2900, kd: 50, intent: 'I', tier: 5, priority: 'q3-q4', suggestedUrl: '/blog/what-is-mes' },
  { id: 124, keyword: 'what is shop floor control', vol: 390, kd: 30, intent: 'I', tier: 5, priority: 'q2', suggestedUrl: '/blog/what-is-shop-floor-control' },
  { id: 125, keyword: 'what is capacity planning', vol: 1600, kd: 35, intent: 'I', tier: 5, priority: 'q2', suggestedUrl: '/blog/what-is-capacity-planning' },
  { id: 126, keyword: 'what is bottleneck in production', vol: 390, kd: 25, intent: 'I', tier: 5, priority: 'q2', suggestedUrl: '/blog/what-is-bottleneck-production' },
  { id: 127, keyword: 'what is takt time', vol: 3600, kd: 35, intent: 'I', tier: 5, priority: 'q2', suggestedUrl: '/blog/what-is-takt-time' },
  { id: 128, keyword: 'what is cycle time', vol: 2900, kd: 40, intent: 'I', tier: 5, priority: 'q3-q4', suggestedUrl: '/blog/what-is-cycle-time' },
  { id: 129, keyword: 'what is lead time', vol: 4400, kd: 45, intent: 'I', tier: 5, priority: 'q3-q4', suggestedUrl: '/blog/what-is-lead-time' },
  { id: 130, keyword: 'what is work in process', vol: 1900, kd: 35, intent: 'I', tier: 5, priority: 'q3-q4', suggestedUrl: '/blog/what-is-work-in-process' },
  { id: 131, keyword: 'MRP vs ERP', vol: 3600, kd: 45, intent: 'I', tier: 5, priority: 'q2', suggestedUrl: '/blog/mrp-vs-erp' },
  { id: 132, keyword: 'MRP vs MRP II', vol: 720, kd: 30, intent: 'I', tier: 5, priority: 'q2', suggestedUrl: '/blog/mrp-vs-mrp-ii' },
  { id: 133, keyword: 'MRP vs APS', vol: 480, kd: 25, intent: 'I', tier: 5, priority: 'now', suggestedUrl: '/blog/mrp-vs-aps' },
  { id: 134, keyword: 'APS vs ERP', vol: 210, kd: 22, intent: 'I', tier: 5, priority: 'q2', suggestedUrl: '/blog/aps-vs-erp-scheduling' },
  { id: 135, keyword: 'MES vs ERP', vol: 590, kd: 32, intent: 'I', tier: 5, priority: 'q3-q4', suggestedUrl: '/blog/mes-vs-erp' },
  { id: 136, keyword: 'MES vs SCADA', vol: 480, kd: 30, intent: 'I', tier: 5, priority: 'q3-q4', suggestedUrl: '/blog/mes-vs-scada' },
  { id: 137, keyword: 'finite vs infinite capacity scheduling', vol: 90, kd: 15, intent: 'I', tier: 5, priority: 'now', suggestedUrl: '/blog/finite-vs-infinite-capacity-scheduling' },
  { id: 138, keyword: 'push vs pull production', vol: 880, kd: 30, intent: 'I', tier: 5, priority: 'q2', suggestedUrl: '/blog/push-vs-pull-production' },
  { id: 139, keyword: 'make to order vs make to stock', vol: 720, kd: 28, intent: 'I', tier: 5, priority: 'q2', suggestedUrl: '/blog/make-to-order-vs-make-to-stock' },
  { id: 140, keyword: 'job shop vs flow shop', vol: 390, kd: 25, intent: 'I', tier: 5, priority: 'q2', suggestedUrl: '/blog/job-shop-vs-flow-shop' },
  { id: 141, keyword: 'kanban vs scrum', vol: 4400, kd: 55, intent: 'I', tier: 5, priority: 'q3-q4', suggestedUrl: '/blog/kanban-vs-scrum' },
  { id: 142, keyword: 'lean vs six sigma', vol: 2400, kd: 50, intent: 'I', tier: 5, priority: 'q3-q4', suggestedUrl: '/blog/lean-vs-six-sigma' },
  { id: 143, keyword: 'theory of constraints', vol: 4400, kd: 45, intent: 'I', tier: 5, priority: 'q2', suggestedUrl: '/blog/theory-of-constraints' },
  { id: 144, keyword: 'drum buffer rope scheduling', vol: 260, kd: 22, intent: 'I', tier: 5, priority: 'now', suggestedUrl: '/blog/drum-buffer-rope-scheduling' },
  { id: 145, keyword: 'theory of constraints scheduling', vol: 390, kd: 28, intent: 'I', tier: 5, priority: 'now', suggestedUrl: '/blog/theory-of-constraints-scheduling' },
  { id: 146, keyword: 'production scheduling methods', vol: 880, kd: 30, intent: 'I', tier: 5, priority: 'now', suggestedUrl: '/blog/production-scheduling-methods' },
  { id: 147, keyword: 'production scheduling techniques', vol: 320, kd: 25, intent: 'I', tier: 5, priority: 'q2', suggestedUrl: '/blog/production-scheduling-techniques' },
  { id: 148, keyword: 'production scheduling algorithms', vol: 390, kd: 35, intent: 'I', tier: 5, priority: 'q3-q4', suggestedUrl: '/blog/production-scheduling-algorithms' },
  { id: 149, keyword: 'bottleneck scheduling', vol: 320, kd: 25, intent: 'I', tier: 5, priority: 'q2', suggestedUrl: '/blog/bottleneck-scheduling' },
  { id: 150, keyword: 'backward scheduling', vol: 590, kd: 28, intent: 'I', tier: 5, priority: 'q2', suggestedUrl: '/blog/backward-scheduling' },
  { id: 151, keyword: 'forward scheduling', vol: 480, kd: 28, intent: 'I', tier: 5, priority: 'q2', suggestedUrl: '/blog/forward-vs-backward-scheduling' },
  { id: 152, keyword: 'level loading production', vol: 170, kd: 22, intent: 'I', tier: 5, priority: 'q2', suggestedUrl: '/blog/level-loading-production' },
  { id: 153, keyword: "johnson's rule scheduling", vol: 1000, kd: 30, intent: 'I', tier: 5, priority: 'q3-q4', suggestedUrl: '/blog/johnsons-rule-scheduling' },
  { id: 154, keyword: 'SPT scheduling', vol: 320, kd: 25, intent: 'I', tier: 5, priority: 'q3-q4', suggestedUrl: '/blog/spt-scheduling' },
  { id: 155, keyword: 'EDD scheduling', vol: 210, kd: 22, intent: 'I', tier: 5, priority: 'q3-q4', suggestedUrl: '/blog/edd-scheduling' },
  { id: 156, keyword: 'lean manufacturing principles', vol: 2900, kd: 50, intent: 'I', tier: 5, priority: 'q3-q4', suggestedUrl: '/blog/lean-manufacturing-principles' },
  { id: 157, keyword: 'just in time manufacturing', vol: 2400, kd: 48, intent: 'I', tier: 5, priority: 'q3-q4', suggestedUrl: '/blog/just-in-time-manufacturing' },
  { id: 158, keyword: '5S manufacturing', vol: 2900, kd: 45, intent: 'I', tier: 5, priority: 'q3-q4', suggestedUrl: '/blog/5s-methodology-implementation' },
  { id: 159, keyword: 'how to schedule production in a factory', vol: 170, kd: 20, intent: 'I', tier: 5, priority: 'now', suggestedUrl: '/blog/how-to-schedule-production' },
  { id: 160, keyword: 'how to create a production schedule', vol: 590, kd: 28, intent: 'I', tier: 5, priority: 'now', suggestedUrl: '/blog/how-to-create-production-schedule' },
  { id: 161, keyword: 'how to improve production scheduling', vol: 140, kd: 22, intent: 'I', tier: 5, priority: 'q2', suggestedUrl: '/blog/how-to-improve-production-scheduling' },
  { id: 162, keyword: 'how to reduce setup time', vol: 390, kd: 25, intent: 'I', tier: 5, priority: 'q2', suggestedUrl: '/blog/changeover-time-reduction' },
  { id: 163, keyword: 'how to reduce WIP', vol: 170, kd: 22, intent: 'I', tier: 5, priority: 'q2', suggestedUrl: '/blog/how-to-reduce-wip' },
  { id: 164, keyword: 'how to calculate OEE', vol: 1300, kd: 35, intent: 'I', tier: 5, priority: 'q2', suggestedUrl: '/blog/how-to-calculate-oee' },
  { id: 165, keyword: 'how to calculate takt time', vol: 1000, kd: 30, intent: 'I', tier: 5, priority: 'q2', suggestedUrl: '/blog/how-to-calculate-takt-time' },
  { id: 166, keyword: 'how to calculate capacity utilization', vol: 720, kd: 32, intent: 'I', tier: 5, priority: 'q2', suggestedUrl: '/blog/capacity-utilization-rate' },
  { id: 167, keyword: 'how to calculate lead time', vol: 880, kd: 30, intent: 'I', tier: 5, priority: 'q2', suggestedUrl: '/blog/how-to-calculate-lead-time' },
  { id: 168, keyword: 'how to reduce bottlenecks', vol: 210, kd: 22, intent: 'I', tier: 5, priority: 'q2', suggestedUrl: '/blog/how-to-reduce-bottlenecks' },
  { id: 169, keyword: 'how to plan production capacity', vol: 260, kd: 25, intent: 'I', tier: 5, priority: 'q2', suggestedUrl: '/blog/how-to-plan-production-capacity' },
  { id: 170, keyword: 'production scheduling best practices', vol: 320, kd: 25, intent: 'I', tier: 5, priority: 'now', suggestedUrl: '/blog/production-scheduling-best-practices' },
  { id: 171, keyword: 'manufacturing KPIs', vol: 1900, kd: 40, intent: 'I', tier: 5, priority: 'q2', suggestedUrl: '/blog/manufacturing-kpis-guide' },
  { id: 172, keyword: 'production KPIs', vol: 720, kd: 32, intent: 'I', tier: 5, priority: 'q2', suggestedUrl: '/blog/production-kpis' },
  { id: 173, keyword: 'OEE calculation', vol: 1600, kd: 38, intent: 'I', tier: 5, priority: 'q2', suggestedUrl: '/blog/oee-calculation' },
  { id: 174, keyword: 'OEE formula', vol: 1000, kd: 35, intent: 'I', tier: 5, priority: 'q2', suggestedUrl: '/blog/oee-formula' },
  { id: 175, keyword: 'production efficiency formula', vol: 480, kd: 28, intent: 'I', tier: 5, priority: 'q2', suggestedUrl: '/blog/production-efficiency-formula' },
  { id: 176, keyword: 'capacity utilization formula', vol: 590, kd: 30, intent: 'I', tier: 5, priority: 'q2', suggestedUrl: '/blog/capacity-utilization-rate' },
  { id: 177, keyword: 'first pass yield', vol: 880, kd: 35, intent: 'I', tier: 5, priority: 'q3-q4', suggestedUrl: '/blog/first-pass-yield' },
  { id: 178, keyword: 'schedule adherence', vol: 480, kd: 28, intent: 'I', tier: 5, priority: 'q3-q4', suggestedUrl: '/blog/schedule-adherence' },
  { id: 179, keyword: 'on time delivery KPI', vol: 390, kd: 25, intent: 'I', tier: 5, priority: 'q3-q4', suggestedUrl: '/blog/on-time-delivery-kpi' },
  { id: 180, keyword: 'perfect order rate', vol: 320, kd: 25, intent: 'I', tier: 5, priority: 'q3-q4', suggestedUrl: '/blog/perfect-order-rate' },
  { id: 181, keyword: 'production scheduling problems', vol: 210, kd: 22, intent: 'I', tier: 5, priority: 'now', suggestedUrl: '/blog/production-scheduling-problems' },
  { id: 182, keyword: 'manufacturing scheduling challenges', vol: 140, kd: 20, intent: 'I', tier: 5, priority: 'now', suggestedUrl: '/blog/manufacturing-scheduling-challenges' },
  { id: 183, keyword: 'why production scheduling fails', vol: 40, kd: 10, intent: 'I', tier: 5, priority: 'q3-q4', suggestedUrl: '/blog/why-production-scheduling-fails' },
  { id: 184, keyword: 'excel scheduling limitations', vol: 50, kd: 10, intent: 'I', tier: 5, priority: 'now', suggestedUrl: '/blog/excel-scheduling-limitations' },
  { id: 185, keyword: 'problems with spreadsheet scheduling', vol: 30, kd: 8, intent: 'I', tier: 5, priority: 'now', suggestedUrl: '/blog/problems-with-spreadsheet-scheduling' },
  { id: 186, keyword: 'replacing excel for production planning', vol: 40, kd: 10, intent: 'I', tier: 5, priority: 'now', suggestedUrl: '/blog/excel-to-aps-migration-guide' },
  { id: 187, keyword: 'when to upgrade from excel', vol: 90, kd: 15, intent: 'I', tier: 5, priority: 'q2', suggestedUrl: '/blog/when-to-upgrade-from-excel' },
  { id: 188, keyword: 'production scheduling software features', vol: 90, kd: 18, intent: 'I', tier: 5, priority: 'q2', suggestedUrl: '/blog/production-scheduling-software-features' },
  { id: 189, keyword: 'what to look for in scheduling software', vol: 70, kd: 15, intent: 'I', tier: 5, priority: 'q2', suggestedUrl: '/blog/what-to-look-for-in-scheduling-software' },
  { id: 190, keyword: 'scheduling software buying guide', vol: 110, kd: 18, intent: 'I', tier: 5, priority: 'q2', suggestedUrl: '/blog/scheduling-software-buying-guide' },
  { id: 191, keyword: 'manufacturing software selection', vol: 170, kd: 25, intent: 'I', tier: 5, priority: 'q3-q4', suggestedUrl: '/blog/manufacturing-software-selection' },
  { id: 192, keyword: 'APS software features', vol: 90, kd: 18, intent: 'I', tier: 5, priority: 'q2', suggestedUrl: '/blog/aps-software-features' },
  { id: 193, keyword: 'how much does production scheduling software cost', vol: 50, kd: 12, intent: 'C', tier: 5, priority: 'q2', suggestedUrl: '/blog/production-scheduling-software-cost' },

  // ─────────────── LOCAL ───────────────
  { id: 194, keyword: 'manufacturing software company', vol: 480, kd: 40, intent: 'C', tier: 'local', priority: 'q2', suggestedUrl: '/about' },
  { id: 195, keyword: 'production scheduling consultant', vol: 170, kd: 28, intent: 'C', tier: 'local', priority: 'q2', suggestedUrl: '/consulting' },
  { id: 196, keyword: 'manufacturing software Michigan', vol: 30, kd: 15, intent: 'C', tier: 'local', priority: 'now', suggestedUrl: '/about' },
  { id: 197, keyword: 'production planning consultant USA', vol: 40, kd: 18, intent: 'C', tier: 'local', priority: 'q3-q4', suggestedUrl: '/consulting' },
  { id: 198, keyword: 'APS implementation services', vol: 70, kd: 22, intent: 'C', tier: 'local', priority: 'q3-q4', suggestedUrl: '/consulting' },

  // ─────────────── BRAND ───────────────
  { id: 199, keyword: 'User Solutions RMDB', vol: 70, kd: 5, intent: 'T', tier: 'brand', priority: 'now', suggestedUrl: '/resource-manager-db-2' },
  { id: 200, keyword: 'Resource Manager DB', vol: 140, kd: 8, intent: 'T', tier: 'brand', priority: 'now', suggestedUrl: '/resource-manager-db-2' },
  { id: 201, keyword: 'EDGEBI software', vol: 40, kd: 5, intent: 'T', tier: 'brand', priority: 'now', suggestedUrl: '/edgebi' },
  { id: 202, keyword: 'Resource Manager for Excel', vol: 90, kd: 8, intent: 'T', tier: 'brand', priority: 'now', suggestedUrl: '/resource-manager-for-excel-2' },
  { id: 203, keyword: 'JSL Job Scheduler', vol: 30, kd: 5, intent: 'T', tier: 'brand', priority: 'now', suggestedUrl: '/jsl-job-scheduler-lite' },
  { id: 204, keyword: 'User Solutions Inc', vol: 210, kd: 10, intent: 'T', tier: 'brand', priority: 'now', suggestedUrl: '/about' },
  { id: 205, keyword: 'usersolutions.com', vol: 90, kd: 5, intent: 'T', tier: 'brand', priority: 'now', suggestedUrl: '/' }
];
