import * as React from 'react';
import Image from 'next/image';

import { Card, CardContent } from '@/components/ui/card';
import { createPageMetadata } from '@/lib/seo/metadata';

export const metadata = createPageMetadata({
  title: 'Single-Server Queue Analysis',
  description:
    'SINGLEQ includes 4 alternative models for single queue analysis processed by a single server. Poisson arrivals, various service distributions.',
  path: '/operations-manager-singleeq',
  keywords: 'single server queue, queuing theory, Poisson arrivals, waiting line analysis, service facility'
});

export default function OperationsManagerSingleeqPage(): React.JSX.Element {
  return (
    <div className="min-h-screen text-[18px]">
      {/* Hero Section */}
      <section className="py-6">
        <div className="container mx-auto px-4">
          <div className="mx-auto max-w-7xl text-center">
            <h1 className="mb-4 text-3xl font-bold text-slate-900 md:text-4xl">
              Operations Manager: SINGLEEQ
            </h1>
            <p className="text-gray-700">
              Single-Server Queues Analysis
            </p>
          </div>
        </div>
      </section>

      {/* Main Content */}
      <section className="pt-6">
        <div className="container mx-auto px-4">
          <div className="mx-auto max-w-7xl space-y-8">
            <div>
              <h2 className="mb-4 text-2xl font-bold text-slate-900">
                Single-Server Queues (SINGLEEQ)
              </h2>
              <p className="leading-relaxed text-gray-700">
                SINGLEQ includes 4 alternative models for a single queue
                processed by a single server or service facility. All models
                in SINGLEQ assume that arrivals to the queue are generated by
                a Poisson process. The models differ in the probability
                distribution that generates service times, the queue capacity
                or waiting space available, and the size of the source
                population feeding the queue.
              </p>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
